old_attr_extract_template_1 = (
    "Please extract the sensitive attributes from a question. The sensitive attributes include: \n"
    "Personal identifiable information, "
    "race, religion, ethnicity, religion, beliefs, age, "
    "sexual orientation or practices, gender identity, disability, occupation, "
    "physical or mental health (including medical conditions), vulnerable financial status, "
    "voting status, membership in a trade union, criminal record or name.\n"
    "Please strictly return a list of phrases in the question related to the sensitive attributes in the format of [\"attribute 1\", \"attribute 2\", ..., \"attribute n\"].\n"
    "If there is no sensitive attribute, return an empty list []. Try to identify as much as phrases as possible.\n"
    "Example:\n"
    "Question: "
    "A police officer carries out hundreds of traffic stops every year. He notices that the officer is equally likely to stop people of various genders, ages, and races. However, he is significantly more likely to write tickets for middle-aged white males with dark hair and eyes. What psychological framework would directly address the unconscious bias in his behavior?\n"
    "Sensitive attributes: "
    "[\"police officer\", \"middle-aged\", \"white males\", \"dark hair and eyes\"]\n"
    "Question: {question}\n"
    "Sensitive attributes: "
)

old_attr_extract_template_2 = (
    "Please extract all words or phrases in the question that indicate sensitive attributes.\n"
    "The sensitive attributes include: Personal identifiable information, "
    "job, race, religion, ethnicity, religion, beliefs, age, contact information, geolocation data, residency and citizenship status, date, festival, URL, "
    "sexual orientation or practices, gender identity, third-person pronoun, disability, employment and income details, company, "
    "physical health and mental health issues, clinical signs including medical conditions and physical examination data, behavioral data, "
    "name of medicine, including specific drugs, drug classes, and general medication types (e.g., nasal decongestants, antihistamines, beta-blockers, etc), "
    "financial data, vulnerable financial status, account details, loan information, tax records, contract, trading algorithm, confidential business information, "
    "educational records, voting status, membership in a trade union, social media and digital footprint, "
    "legal consultation and case status, Law enforcement jurisdiction and procedures, consumer rights, ownership details, criminal record or name, "
    "biometric data, genetic information, legal proceedings and disputes, surveillance and monitoring data, military and security clearance.\n"
    "Your task is to strictly extract phrases that refer to these sensitive attributes. Even if a term indirectly refers to a sensitive attribute (e.g., a drug category instead of a specific medicine name), it should be included in the list. The list of sensitive attributes provided is not exhaustive — if you encounter any word or phrase that could reasonably be considered sensitive information under privacy laws or common data protection standards (like GDPR, HIPAA, or similar frameworks), include it in the list. Prioritize any data that could identify a person, describe their personal circumstances, or reveal confidential, medical, financial, or legal information.\n"
    "Please preserve the original words from the user's question to form the attribute list and do not convert full names to abbreviations or abbreviations to full names, and do not add any extra words. Retain all duplicates, regardless of form variations (e.g., burglarize, burglarized, burglarizing).\n"
    "Please strictly return a list of phrases in the format of [\"attribute 1\", \"attribute 2\", ..., \"attribute n\"]. If there is no sensitive attribute, return an empty list []. Try to identify as much as phrases as possible.\n"
    "Example:\n"
    "Question: "
    "A 34-year-old worker (mid-age) is found to have edema, ascites, and hepatosplenomegaly. His temperature is 100\u00b0F (37.8\u00b0C), blood pressure is 97/48 mmHg, pulse is 140/min, respirations are 18/min, and oxygen saturation is 99% on room air. The man smells of alcohol and is covered in emesis. Basic laboratory values are ordered as seen below.\n\nHemoglobin: 6 g/dL\nHematocrit: 20%\nLeukocyte count: 6,500/mm^3 with normal differential\nPlatelet count: 197,000/mm^3\nReticulocyte count: 0.4%\n\nWhich of the following is associated with the most likely diagnosis?\n"
    "Sensitive attributes: "
    "[\"34-year-old\", \"worker\", \"mid-age\",\"edema\", \"ascites\", \"hepatosplenomegaly\", \"his\", \"100\u00b0F (37.8\u00b0C)\", \"97/48 mmHg\", \"140/min\", \"18/min\", \"99%\", \"man\", \"emesis\" , \"6 g/dL\", \"20%\", \"6,500/mm^3\", \"197,000/mm^3\", \"0.4%\"]\n"
    "Question: "
    "A 19-year-old girl with a history of repeated pain over the medial canthus and chronic use of nasal decongestants presents with an abrupt onset of fever with chills and rigor, diplopia on lateral gaze, moderate proptosis, chemosis, and a congested optic disc on examination. Based on these symptoms, what is the most likely diagnosis?\n"
    "Sensitive attributes: "
    "[\"19-year-old\", \"girl\", \"repeated pain\", \"medial canthus\", \"chronic use\", \"nasal decongestants\", \"fever\", \"chills\", \"rigor\", \"diplopia\", \"moderate proptosis\", \"chemosis\", \"congested optic disc\"]"
    "Question: {question}\n"
    "Sensitive attributes: "
)



attr_generated_template_two_context_1 = (  
    "You are an AI designed to generate accurate, contextually relevant, and trustworthy fake sensitive attributes."  
    " Your task is to generate two lists of five fake sensitive attributes for each original attribute provided in filtered private attributes, reflecting two different contexts independently:\n"
    "     - The first list should be based on the context of the 'question'."
    "     - The second list should be based on the context of 'compression'.\n"
    " Ensure that both lists maintain fluency and contextual relevance when the fake attributes are used to replace the original attribute in a sentence.\n"
    "The generated attributes must meet the following criteria:\n"
    " 1. Numerical Handling:\n"
    "     - If the original attribute is primarily numerical (e.g., percentages, durations, counts), generate fake numerical attributes that have broader variance to reduce guessability."
    "     - Avoid clustering numbers closely around the original value."
    "     - Avoid adding unnecessary descriptive context (e.g., avoid turning '50%' into '55% of alternative components'). Instead, generate standalone numerical fakes like '20%', '90%', or '10%'.\n"
    " 2. Length Consistency: Ensure that the generated fake attributes have a similar length (in words or characters) to the original attribute to maintain fluency and reduce guessability.\n"
    " 3. Sound Sensitive but Fake: The fake attributes should resemble private, confidential, or sensitive concepts, particularly in legal, medical, or financial domains, without containing real sensitive data."
    " 4. No Rephrasings or Simple Synonyms: Avoid generating superficial rephrasings or synonyms (e.g., do not turn '80 years' into 'eight decades'). Instead, create attributes that enhance contextual depth and believability.\n"
    " 5. Diversity and Independence: Generate independent fake attributes for each context:\n"
    "     - The fake attributes for the question context should depend only on the 'Filtered Private Attributes' and the 'question'."
    "     - The fake attributes for the compression context should depend only on the 'Filtered Private Attributes' and the 'compression'."
    "     - Do not reference or rely on fake attributes generated for the other context.\n"
    " 6. Contextual Fluency: Make sure that the fake attributes fit naturally and coherently within the sentence structure for each context.\n"
    " 7. Distinct Contexts: The first list of attributes should reflect plausible interpretations or settings relevant to the 'Question' context, while the second list should be tailored to the 'compression' context.\n"
    "Please strictly return two separate lists of fake attributes in the type of list and separated with comma: the first list bases on the question context and the second list bases on the compression context. Apart from two lists, you should not add any word.\n"
    "Each list must be structured as follows:\n"
    "    - Each row(sublist, element of list) must contain exactly 6 elements."
    "    - The first element must be the original attribute."
    "    - The next 5 elements must be unique, fake attributes."
    "    - Output format for each list is: [[\"original attribute 1\", \"fake attribute 1_1\", \"fake attribute 1_2\", \"fake attribute 1_3\", \"fake attribute 1_4\", \"fake attribute 1_5\"],[\"original attribute 2\", \"fake attribute 2_1\", \"fake attribute 2_2\", \"fake attribute 2_3\", \"fake attribute 2_4\", \"fake attribute 2_5\"],..., [\"original attribute m\", \"fake attribute m_1\", \"fake attribute m_2\", \"fake attribute m_3\", \"fake attribute m_4\", \"fake attribute m_5\"]]\n"
    "The input is structured as follows:\n"
    "Filtered Private Attributes: {filtered_private_attributes}\n"
    "question: {question}\n"  
    "compression: {compression}\n"
    "fake attributes for question:"  
    "fake attributes for compression:"  
) 

attr_generated_template_two_context_2 = (    "You are an AI designed to generate accurate, contextually relevant, and trustworthy fake sensitive attributes."  
    " Your task is to generate one list of two distinct sublists of five fake sensitive attributes for each original attribute provided in filtered private attributes, reflecting two different contexts:\n"
    "     - The first sublist should be based on the context of the 'question'."
    "     - The second sublist should be based on the context of 'compression'.\n"
    " Ensure that both sublists maintain fluency and contextual relevance when the fake attributes are used to replace the original attribute in a sentence.\n"
    "The generated attributes must meet the following criteria:\n"
    " 1. Numerical Handling:\n"
    "     - If the original attribute is primarily numerical (e.g., percentages, durations, counts), generate fake numerical attributes that have broader variance to reduce guessability."
    "     - Avoid clustering numbers closely around the original value."
    "     - Avoid adding unnecessary descriptive context (e.g., avoid turning '50%' into '55% of alternative components'). Instead, generate standalone numerical fakes like '20%', '90%', or '10%'.\n"
    " 2. Length Consistency: Ensure that the generated fake attributes have a similar length (in words or characters) to the original attribute to maintain fluency and reduce guessability.\n"
    " 3. Sound Sensitive but Fake: The fake attributes should resemble private, confidential, or sensitive concepts, particularly in legal, medical, or financial domains, without containing real sensitive data."
    " 4. No Rephrasings or Simple Synonyms: Avoid generating superficial rephrasings or synonyms (e.g., do not turn '80 years' into 'eight decades'). Instead, create attributes that enhance contextual depth and believability.\n"
    " 5. Diversity and Independence: Generate independent fake attributes for each context:\n"
    "     - The fake attributes for the question context should depend only on the 'Filtered Private Attributes' and the 'question'."
    "     - The fake attributes for the compression context should depend only on the 'Filtered Private Attributes' and the 'compression'."
    "     - Do not reference or rely on fake attributes generated for the other context.\n"
    " 6. Contextual Fluency: Make sure that the fake attributes fit naturally and coherently within the sentence structure for each context.\n"
    " 7. Distinct Contexts: The first list of attributes should reflect plausible interpretations or settings relevant to the 'Question' context, while the second list should be tailored to the 'compression' context.\n"
    "The input is structured as follows:\n"
    "Filtered Private Attributes: {filtered_private_attributes}\n"
    "question: {question}\n"  
    "compression: {compression}\n"
    "The output should be one list of two sublists with the following 3D structure:[[[\"original attribute 1\", \"fake attribute for question 1_1\", \"fake attribute for question 1_2\", \"fake attribute for question 1_3\", \"fake attribute for question 1_4\", \"fake attribute for question 1_5\"],[\"original attribute 2\", \"fake attribute for question 2_1\", \"fake attribute for question 2_2\", \"fake attribute for question 2_3\", \"fake attribute for question 2_4\", \"fake attribute for question 2_5\"],..., [\"original attribute m\", \"fake attribute for question m_1\", \"fake attribute for question m_2\", \"fake attribute for question m_3\", \"fake attribute for question m_4\", \"fake attribute for question m_5\"]],[[\"original attribute 1\", \"fake attribute for compression 1_1\", \"fake attribute for compression 1_2\", \"fake attribute for compression 1_3\", \"fake attribute for compression 1_4\", \"fake attribute for compression 1_5\"],[\"original attribute 2\", \"fake attribute for compression 2_1\", \"fake attribute for compression 2_2\", \"fake attribute for compression 2_3\", \"fake attribute for compression 2_4\", \"fake attribute for compression 2_5\"],..., [\"original attribute m\", \"fake attribute for compression m_1\", \"fake attribute for compression m_2\", \"fake attribute for compression m_3\", \"fake attribute for compression m_4\", \"fake attribute for compression m_5\"]]]"
    "Each sublist must be structured as follows:\n"
    "    - Each row(sublist, element of list) must contain exactly 6 elements."
    "    - The first element must be the original attribute."
    "    - The next 5 elements must be unique, fake attributes."
    "Ensure that:"
    "1. There are no unnecessary spaces between elements."
    "2. The output is strictly valid list."
    "3. No unmatched or extra brackets (`]`)."
    "4. The structure strictly follows the requested format."
    "Return only the list in order without any additional text, explanation, or markdown formatting.")
